UniversityMvc/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UniversityMvc.Areas.Identity.Data;
using UniversityMvc.Models;

namespace UniversityMvc.Controllers
{
    public class AdminController : Controller
    {
        private readonly AdminDbContext _adminDbContext;
        public AdminController(AdminDbContext adminDbContext)
        {
            _adminDbContext = adminDbContext;
        }

        public IActionResult Approve(Admin adminModels)
        {

            adminModels.StatusIsApprove = "Approved";
            _adminDbContext.AdminModels.Update(adminModels);
            _adminDbContext.SaveChanges();
            return View("Index", adminModels);
        }
        public IActionResult Reject(Admin adminModels)
        {
            adminModels.StatusIsApprove = "Rejected";
            _adminDbContext.AdminModels.Update(adminModels);
            _adminDbContext.SaveChanges();
            return View("Index", adminModels);
        }
        [Authorize(Policy = "writeonly")]
        public IActionResult Index()
        {
            if (_adminDbContext.AdminModels == null)
            {
                return NotFound();
            }
            List<Admin> adminModels = new List<Admin>();
            adminModels = _adminDbContext.AdminModels.Where(x => x.StatusIsApprove == "Pending").ToList();
            if (adminModels == null)
            {
                return NotFound();
            }
            return View(adminModels);

        }

    }
}
   

UniversityMvc/Controllers/UniversityController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UniversityClassLibrary.Entities;
using UniversityMvc.Models;

namespace UniversityMvc.Controllers
{
    public class UniversityController : Controller
    {
        public readonly IWebHostEnvironment _webHostEnvironment;
        Uri baseAddress = new Uri("https://localhost:7272/api");

        HttpClient client;
        private readonly IMapper _mapper;
        public UniversityController(IWebHostEnvironment webHostEnvironment,IMapper mapper)
        {
            client = new HttpClient();
            _webHostEnvironment = webHostEnvironment;
            client.BaseAddress = baseAddress;
            _mapper = mapper;

        }
        //public static List<UniversityViewModel> university = new List<UniversityViewModel>();

        [Authorize(Policy= "readonly")]
        public IActionResult Index()
        {
            
            HttpResponseMessage response = client.GetAsync(baseAddress + "/UniversityDetails/GetUniversity").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                var uni = JsonConvert.DeserializeObject<List<UniversityDetails>>(data);
                var uniList = _mapper.Map<List<UniversityViewModel>>(uni);

                return View("Index", uniList);
            }
            else
            {
                return View();
            }

        }
        public IActionResult AddNewUniversity()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddNewUniversity(UniversityViewModel university)
        {
            try
            {
                HttpRequestMessage request = new HttpRequestMessage();
                var data = JsonConvert.SerializeObject(university);
                var contentData = new StringContent(data, System.Text.Encoding.UTF8, "application/json");
                HttpResponseMessage respnse = client.PostAsync(baseAddress + "/UniversityDetails/PostUniversityDetails", contentData).Result;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return Content("ohhh");
            }
        }
        
        public ActionResult DeleteUniversityDeatils(int id)
        {

            //HTTP DELETE
            List<UniversityViewModel> university = new List<UniversityViewModel>();
            var deleteTask = client.DeleteAsync(baseAddress + "/UniversityDetails/DeleteUniversityDetails/" + id);
            deleteTask.Wait();

            var result = deleteTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View("Index",university);
        }

        public ActionResult UpdateUniversity1(int id)
        {
            UniversityViewModel? university = new();

            HttpResponseMessage responseMessage = client.GetAsync(baseAddress + "/UniversityDetails/GetUniversityDetails/" + id.ToString()).Result;
            if (responseMessage.IsSuccessStatusCode)
            {
                string data = responseMessage.Content.ReadAsStringAsync().Result;
                university = JsonConvert.DeserializeObject<UniversityViewModel>(data);
            }
            return View(university);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateUniversity(UniversityViewModel university)
        {

            var putTask = client.PutAsJsonAsync<UniversityViewModel>(baseAddress + "/UniversityDetails/PutUniversityDetails/" + university.UniversityId.ToString(), university);
            putTask.Wait();

            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View(university);
        }



        [HttpGet]
        public ActionResult Details(int id)
        {

            HttpResponseMessage response = client.GetAsync(baseAddress + "/UniversityDetails/UniversityDetailsExists/id?id=" + id).Result;
            string data = response.Content.ReadAsStringAsync().Result;
            UniversityViewModel university = JsonConvert.DeserializeObject<UniversityViewModel>(data)!;
            return View("Details",university);


        }


    }
}

UniversityMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniversityMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniversityMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniversityMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="University" asp-action="Index">ListofUniversities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="University" asp-action="AddNewUniversity">AddNewUniversity</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">AdminPortal</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"></partial>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UniversityMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UniversityMvc/Views/Shared/_PartialViewForCreate.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<p>
    <a asp-action="AddNewUniversity">ListOfUniversities</a>
</p>